sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  - "$HOME/llvm-build-9.0.0"
  - "$HOME/llvm-src-9.0.0"

matrix:
  include:
  - ghc: 8.8.2
  
install:
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 9
  - ghc --version
  - cabal --version
  - cabal update
  - cabal build --enable-tests

script:
  - cabal test all --enable-tests

notifications:
  email: false
