sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

env:
  global:
    - LLVM_VER=9.0.0

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  - "$HOME/llvm-build-$LLVM_VER"
  - "$HOME/llvm-src-$LLVM_VER"

before_install:
 - export LD_LIBRARY_PATH=$HOME/llvm-build-${LLVM_VER}/lib:$LD_LIBRARY_PATH
 - export PATH=$HOME/llvm-build-${LLVM_VER}/bin:$PATH
 - mkdir -p $HOME/bin
 - export PATH=$HOME/bin:$PATH

install:
 - curl -L https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5.tar.gz | tar -xzf - -C $HOME
 - export PATH=$HOME/cmake-3.15.5-Linux-x86_64/bin:$PATH
 - curl -L https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
 - unzip ninja-linux.zip -d $HOME/bin
 - curl http://releases.llvm.org/${LLVM_VER}/llvm-${LLVM_VER}.src.tar.xz | tar -xJf - -C $HOME
 - rsync -ac $HOME/llvm-${LLVM_VER}.src/ $HOME/llvm-src-${LLVM_VER}
 - cd $HOME/llvm-src-${LLVM_VER}
 - mkdir -p build && cd build
 - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=-O0 -DCMAKE_INSTALL_PREFIX=$HOME/llvm-build-${LLVM_VER} -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_BUILD_LLVM_DYLIB=True -DLLVM_LINK_LLVM_DYLIB=True -GNinja ..
 - ninja -j3 install
 - cd $TRAVIS_BUILD_DIR
 - ln -s $HOME/llvm-build-${LLVM_VER}/bin/llvm-config $HOME/bin/llvm-config
 - llvm-config --version

matrix:
  include:
  - ghc: 8.8.2
  
  - ghc: 8.8.2
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal update
      cabal build --enable-tests
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      stack build --system-ghc --test --no-run-tests --no-run-benchmarks --ghc-options=-Werror
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal test all --enable-tests
    else
      stack test --system-ghc
    fi

  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

notifications:
  email: false
